---
- name: Get XML from {{ item }}
  virt:
    name: '{{ item }}'
    command: get_xml
  register: domain_xml

- name: Extract mac address
  xml:
    xmlstring: '{{ domain_xml.get_xml }}'
    xpath: /domain/devices/interface[@type='network']/mac
    content: attribute
  register: result

- name: Wait for the VMs to get an IP
  shell: 'virsh net-dhcp-leases {{ libvirt_network }} | grep {{ result.matches[0].mac.address }} | awk ''{gsub(/\/.*/, "", $5); print $5}'''
  become: yes
  register: ip
  until: ip.stdout != ""
  retries: 60
  delay: 3
  changed_when: false

- set_fact:
    ips: "{{ ips }} + [ '{{ ip.stdout }}' ]"

- name: Add new masters
  add_host:
    hostname: '{{ item }}'
    ansible_ssh_host: '{{ ip.stdout }}'
    groups: 'nodes, masters'
    libvirt_ip_address: '{{ ip.stdout }}'
  when: item in masters

- name: Add new nodes
  add_host:
    hostname: '{{ item }}'
    ansible_ssh_host: '{{ ip.stdout }}'
    groups: 'nodes, {{ cluster_name }}'
    ansible_ssh_user: '{{ ansible_user }}'
    libvirt_ip_address: '{{ ip.stdout }}'
  when: item not in masters
