---
- name: Get pool info
  virt_pool:
    command: info
  register: pools

- name: Destroy VMs
  include_tasks: destroy_vm.yml
  with_items:
    - '{{ instances }}'

- name: Remove known_hosts entries
  lineinfile:
    path: ~/.ssh/known_hosts
    regexp: '{{ item }},'
    state: absent
  with_items:
    - '{{ instances }}'

- name: Remove from /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '{{ item }}'
    state: absent
  with_items:
    - '{{ instances }}'
  when: manage_dns | bool

- name: Revert DNS changes
  include_tasks: configure_dns.yml
  become: true
  when: manage_dns | bool
